### ISSUE TITLE
Mapa mental

### ISSUE THREAD

**Issue by Rosa218** [SistemasTecTlaxiaco/mapa-mental-web-3-Rosa218#1]
[web 3.0 (1).pdf](https://github.com/SistemasTecTlaxiaco/mapa-mental-web-3-Rosa218/files/8423015/web.3.0.1.pdf)

**Comment by josealfredo79** [comment]
Falta la calificacion...

**Comment by josealfredo79** [comment]
Calificacion: 18 Bien hecho y revisada...
